# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

sign_num <- function(x) {
    .Call('_BSATV_sign_num', PACKAGE = 'BSATV', x)
}

ddloglik <- function(knot, facility, delta, z, b_spline, theta, number_facility = 1L) {
    .Call('_BSATV_ddloglik', PACKAGE = 'BSATV', knot, facility, delta, z, b_spline, theta, number_facility)
}

stratify <- function(knot, tol, facility, delta, z, b_spline, max_iteration = 5000L) {
    .Call('_BSATV_stratify', PACKAGE = 'BSATV', knot, tol, facility, delta, z, b_spline, max_iteration)
}

ddloglik_stratify <- function(knot, facility, z, delta, b_spline, theta, number_facility = 1L) {
    .Call('_BSATV_ddloglik_stratify', PACKAGE = 'BSATV', knot, facility, z, delta, b_spline, theta, number_facility)
}

GDboost_stratify <- function(knot, rate, facility, delta, z, b_spline, theta) {
    .Call('_BSATV_GDboost_stratify', PACKAGE = 'BSATV', knot, rate, facility, delta, z, b_spline, theta)
}

GDboost_stratify_no_GD2 <- function(knot, rate, facility, delta, z, b_spline, theta) {
    .Call('_BSATV_GDboost_stratify_no_GD2', PACKAGE = 'BSATV', knot, rate, facility, delta, z, b_spline, theta)
}

dloglik_likelihood_stratify <- function(knot, facility, delta, z, b_spline, theta) {
    .Call('_BSATV_dloglik_likelihood_stratify', PACKAGE = 'BSATV', knot, facility, delta, z, b_spline, theta)
}

ddloglik_gradient <- function(knot, facility, z, delta, b_spline, theta, number_facility = 1L) {
    .Call('_BSATV_ddloglik_gradient', PACKAGE = 'BSATV', knot, facility, z, delta, b_spline, theta, number_facility)
}

GDboost_gradient <- function(knot, rate, facility, delta, z, b_spline, theta) {
    .Call('_BSATV_GDboost_gradient', PACKAGE = 'BSATV', knot, rate, facility, delta, z, b_spline, theta)
}

dloglik_likelihood_gradient <- function(knot, facility, delta, z, b_spline, theta) {
    .Call('_BSATV_dloglik_likelihood_gradient', PACKAGE = 'BSATV', knot, facility, delta, z, b_spline, theta)
}

